oc new-project postgresapiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mbk-documentstore
    name: mbk-documentstore
  namespace: lab
spec:
  selector:
    matchLabels:
      app: mbk-documentstore
  template:
    metadata:
      labels:
        app: mbk-documentstore
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: bdadmin
          - name: PGDATA
            value: /temp/data
      image: cir.chp.belastingdienst.nl/quayio/enterprisedb/postgresql@sha256:5c6c9ddcb8a3565dc593c9d4454872a3bc6cd091b756a9618fec5de2aa974d8f
      imagePullPolicy: Always
      name: postgres
    ports:
      - containerPort: 5432
        protocol: TCP
    resources:
      limits:
        cpu: 60m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 128Mi
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mbk-documentstore
  name: mbk-documentstore
  namespace: postgres
spec:
  ports:
    - name: http
      port: 5432
      protocol: TCP
  selector:
    app: mbk-documentstore